
  /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  */

#include <stdio.h>
#include <stdlib.h>

int main(){

  long sum = 0;
  long arr[3];
  arr[0]=1;
  arr[1]=1;
  arr[2]=0;
  
  while (arr[2]<=4000){
    arr[2]=arr[0]+arr[1];
    printf("arr[2]=%lu\n",sum);
    if(arr[2]%2==0){
      sum+=arr[2];
    }
    arr[0]=arr[1];
    arr[1]=arr[2];
  
  }
  
  printf("sum=%lu\n",sum);
  
  return 0;
}

