CC=gcc
CFLAGS=-Wall -Wextra -Werror -Wshadow -std=c99 -pedantic -g -fwrapv -O2 -m32
OUTFLAG=-o

ALL:
	$(CC) $(CFLAGS) euler_problem_1.c $(OUTFLAG) euler_prob_1.out
	$(CC) $(CFLAGS) euler_problem_2.c $(OUTFLAG) euler_prob_2.out
	$(CC) $(CFLAGS) euler_problem_4.c $(OUTFLAG) euler_prob_4.out
